config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/pro/web'
  post '/rate' => 'rater#create', :as => 'rate'
  get '/faq', to: 'static_pages#faq'
  mount Maily::Engine, at: '/maily' if Rails.env.development?
  mount ActionCable.server, at: '/cable'
  authenticate :overseer, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: 'overseers/inquiries#index'
  get '/overseers', to: redirect('/overseers/dashboard'), as: 'overseer_root'
  get '/customers', to: redirect('/customers/dashboard'), as: 'customer_root'
  get '/suppliers', to: redirect('/suppliers/dashboard'), as: 'supplier_root'

  get '/release_notes', to: 'overseers/site_updates#show'
  post '/release_notes', to: 'overseers/site_updates#create'

  devise_for :overseers, controllers: {sessions: 'overseers/sessions', omniauth_callbacks: 'overseers/omniauth_callbacks'}
  # devise_for :contacts, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords'}, path: :customers

  namespace :suppliers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'suppliers/sessions', passwords: 'suppliers/passwords'}, path: :suppliers
  end

  resources :trainings, only: %i[index show] do
    get :search, on: :collection
  end

  namespace :customers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords'}, path: :customers
  end

  namespace :api do
    namespace :v1 do
      resources :punchouts do
        collection do
          post 'auth'
        end
      end
    end
  end

  namespace 'callbacks' do
    resources :sales_orders do
      member do
        patch 'update'
      end
    end

    resources :sales_invoices do
      member do
        patch 'update'
      end
    end

    resources :sales_receipts

    resources :sales_shipments do
      member do
        patch 'update'
      end
    end

    resources :credit_notes do
      member do
        patch 'update'
      end
    end

    post '1de9b0a30075ae8c303eb420c103c320', to: 'image_readers#update'
    resources :purchase_orders
    resources :products

    get 'login' => '/callbacks/sessions#new'
  end

  namespace 'overseers' do
    resources :customer_feedbacks, only: :index 

    get '/docs/*page' => 'docs#index'
    resources :delivery_challans do
      collection do
        get 'next_step'
      end

      member do
        get 'preview'
        get 'relationship_map'
        get 'get_relationship_map_json'
      end
    end
    resources :payment_collection_emails
    resources :attachments
    resources :review_questions
    resources :banks
    resources :ifsc_codes do
      collection do
        get 'suggestion'
      end
    end

    resource :dashboard, controller: :dashboard do
      get 'chewy'
      get 'reset_index'
      get 'serializer'
      get 'migrations'
      get 'console'
      get 'get_status_records'
      get 'show_email_message_modal'
      post 'update_inquiry'
      post 'update_invoice_request'
      post 'approve_reject_so'
      get 'get_filtered_inquiries'
      get 'get_inquiry_tasks'
      get 'follow_up_dashboard'
      get 'sales_manager'
      get 'accounts'
      get 'sales_executive'
      get 'my_team'
      get 'get_recent_inquiries'
      get 'get_account_executive_data'
    end

    resources :tasks do
      member do
        get 'render_modal_form'
        patch 'add_comment'
      end
      scope module: 'tasks' do
        resources :comments
      end
    end

    resources :remote_requests do
      member do
        get 'show'
      end
      collection do
        get 'resend_failed_requests'
      end
    end

    resources :resync_remote_requests do
      member do
        get 'resend_failed_request'
      end
      collection do
        get 'all_requests'
      end
    end

    resources :callback_requests do
      member do
        get 'show'
      end
    end

    resources :document_creations

    resources :acl_resources do
      collection do
        get 'resource_json'
        get 'menu_resource_json'
      end
    end

    resources :notifications do
      collection do
        post 'mark_as_read'
        get 'queue'
      end
    end

    # resources :reports
    resources :reports do
      member do
        get 'export_report'
      end
    end
    resources :company_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :contact_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :activities, except: [:show] do
      collection do
        get 'pending'
        post 'approve_selected'
        post 'reject_selected'
        post 'add_to_inquiry'
        get 'export_all'
        get 'export_filtered_records'
      end
      member do
        get 'approve'
        get 'reject'
      end
      scope module: 'activities' do
        resources :email_messages do
          collection do
            get 'minutes_of_meeting'
            post 'minutes_of_meeting_notification'
            get 'follow_up_email'
            post 'follow_up_email_notification'
          end
        end
      end
    end

    resource :profile, controller: :profile, except: [:show, :index]
    resources :overseers do
      member do
        patch 'save_acl_resources'
        get 'get_resources'
        get 'get_menu_resources'
        get 'edit_acl'
        patch 'update_acl'
        get 'change_password'
        patch 'update_password'
        get 'becomes'
      end

      collection do
        get 'get_resources'
        get 'isp_report'
        get 'export_isp_report'
      end
    end


    resources :acl_roles do
      member do
        get 'get_acl'
        get 'get_acl_menu'
        get 'get_role_resources'
        post 'save_role'
      end
      collection do
        get 'get_default_resources'
      end
    end

    resources :annual_targets

    resources :exports, except: [:show] do
      collection do
        get 'generate_export'
      end
    end

    resources :suppliers do
      collection do
        get 'customized_index'
        get 'autocomplete'
        get 'export_all'
        get 'export_filtered_records'
      end
    end

    resources :contacts do
      collection do
        get 'autocomplete'
        get 'fetch_company_account'
      end

      member do
        get 'become'
      end
    end

    resources :sales_quotes do
    end

    resources :brands do
      collection do
        get 'autocomplete'
      end
    end

    resources :measurement_units, except: [:show] do
      collection do
        get 'autocomplete'
      end
    end

    resources :tax_codes, except: [:show] do
      collection do
        get 'autocomplete'
        get 'autocomplete_for_product'
      end
    end

    resources :addresses do
      collection do
        get 'autocomplete'
        get 'warehouse_addresses'
        get 'is_sez_params'
        get 'get_gst_code'
      end
    end

    resources :categories do
      collection do
        get 'autocomplete'
        get 'autocomplete_closure_tree'
        get 'export_all'
        get 'autocomplete_active'
      end
    end

    resources :products do
      collection do
        get 'autocomplete'
        get 'non_kit_autocomplete'
        get 'service_autocomplete'
        get 'autocomplete_mpn'
        get 'suggestion'
      end
      member do
        get 'customer_bp_catalog'
        get 'best_prices_and_supplier_bp_catalog'
        get 'sku_purchase_history'
        get 'resync'
        get 'resync_inventory'
        get 'autocomplete_suppliers'
        get 'get_product_details'
      end

      collection do
        get 'autocomplete'
        get 'pending'
        get 'export_all'
        get 'export_filtered_records'
        resources :product_imports, only: [:new, :create] do
          collection do
            get 'excel_template'
          end
        end
      end

      scope module: 'products' do
        resources :comments
      end
    end

    resources :kits do
      member do
      end

      collection do
        get 'autocomplete'
      end
    end

    resources :po_requests do
      member do
        get 'new_purchase_order'
        post 'create_purchase_order'
        get 'manager_amended'
      end
      collection do
        get 'product_resync_inventory'
      end
      scope module: 'po_requests' do
        resources :payment_requests
        resources :email_messages do
          collection do
            get 'sending_po_to_supplier'
            post 'sending_po_to_supplier_notification'
            get 'dispatch_from_supplier_delayed'
            post 'dispatch_from_supplier_delayed_notification'
            get 'material_received_in_bm_warehouse'
            post 'material_received_in_bm_warehouse_notification'
          end
        end
      end

      collection do
        get 'autocomplete'
        get 'pending_and_rejected'
        get 'cancelled'
        get 'under_amend'
        get 'amended'
        get 'pending_stock_approval'
        get 'stock_amend_requests'
        get 'stock'
        get 'completed_stock'
        get 'add_comment'
      end
      member do
        get 'render_modal_form'
        get 'render_cancellation_form'
        get 'reject_purchase_order_modal'
        patch 'rejected_purchase_order'
        patch 'cancel_porequest'
        get 'render_comment_form'
        patch 'add_comment'
      end
    end

    resources :invoice_requests do
      collection do
        get 'autocomplete'
        get 'pending'
        get 'completed'
        get 'cancelled'
      end
      member do
        get 'render_modal_form'
        patch 'cancel_invoice_request'
        patch 'add_comment'
      end
    end

    resources :ar_invoice_requests do
      collection do

app/controllers/overseers/accounts/base_controller.rb
class Overseers::Accounts::BaseController < Overseers::BaseController
  before_action :set_account

  private
    def set_account
      @account = Account.find(params[:account_id])
    end
end

app/controllers/overseers/accounts/companies_controller.rb
class Overseers::Accounts::CompaniesController < Overseers::Accounts::BaseController
  before_action :set_company, only: [:show, :edit, :update]

  def show
    redirect_to edit_overseers_account_company_path(@account, @company)
    authorize_acl @account
  end

  def new
    @company = @account.companies.build(overseer: current_overseer)
    authorize_acl @company
  end

  def index
    base_filter = {
        base_filter_key: 'account_id',
        base_filter_value: params[:account_id]
    }
    authorize_acl @account
    respond_to do |format|
      format.html { }
      format.json do
        service = Services::Overseers::Finders::Companies.new(params.merge(base_filter), current_overseer)
        service.call
        @indexed_companies = service.indexed_records
        @companies = service.records.try(:reverse)
      end
    end
  end

  def payment_collections
    service = Services::Overseers::SalesInvoices::PaymentDashboard.new(@account)
    service.call
    @summery_data = service.summery_data
    base_filter = {
        base_filter_key: 'account_id',
        base_filter_value: @account.id
    }

    authorize_acl :company
    respond_to do |format|
      format.html { }
      format.json do
        service = Services::Overseers::Finders::Companies.new(params.merge(base_filter), current_overseer)
        service.call
        @indexed_companies = service.indexed_records
        @companies = service.records.try(:reverse)
      end
    end
  end


  def ageing_report
    service = Services::Overseers::SalesInvoices::AgeingReport.new(@account)
    service.call
    @summery_data = service.summery_data
    base_filter = {
        base_filter_key: 'account_id',
        base_filter_value: @account.id
    }

    authorize_acl :company
    respond_to do |format|
      format.html { }
      format.json do
        service = Services::Overseers::Finders::Companies.new(params.merge(base_filter), current_overseer)
        service.call
        @indexed_companies = service.indexed_records
        @companies = service.records.try(:reverse)
      end
    end
  end

  def create
    @company = @account.companies.build(company_params.merge(overseer: current_overseer))
    authorize_acl @company

    if @company.save!
      @company.update_attributes(remote_uid: @company.id)
      redirect_to overseers_company_path(@company), notice: flash_message(@company, action_name)
    else
      render 'new'
    end
  end

  def edit
    authorize_acl @company
  end

  def update
    @company.assign_attributes(company_params.merge(overseer: current_overseer))
    authorize_acl @company

    if params[:logistics_owner_id].present? && @company.logistics_owner_id_changed?
      Services::Overseers::PurchaseOrders::UpdateLogisticsOwner.new(@company, current_overseer).call
    end

    options = @company.name_changed? ? { name: @company.name_change[0] } : false

    if @company.save_and_sync(options)
      redirect_to overseers_company_path(@company), notice: flash_message(@company, action_name)
    else
      render 'edit'
    end
  end

  private

    def set_company
      @company ||= Company.find(params[:id])
    end

    def company_params
      params.require(:company).permit(
        :account_id,
          :name,
          :industry_id,
          :credit_limit,
          :remote_uid,
          :default_company_contact_id,
          :default_payment_option_id,
          :default_billing_address_id,
          :default_shipping_address_id,
          :inside_sales_owner_id,
          :outside_sales_owner_id,
          :sales_manager_id,
          :logistics_owner_id,
          :company_type,
          :priority,
          :site,
          :company_creation_request_id,
          :nature_of_business,
          :creadit_limit,
          :tan_proof,
          :pan,
          :pan_proof,
          :cen_proof,
          :logo,
          :is_msme,
          :default_currency,
          :is_active,
          :is_unregistered_dealer,
          :is_international,
          :rating,
          contact_ids: [],
          brand_ids: [],
          product_ids: [],
      )
    end
end

app/controllers/overseers/accounts/sales_invoices_controller.rb
class Overseers::Accounts::SalesInvoicesController < Overseers::Accounts::BaseController
  def show
    authorize_acl :sales_invoice, 'show'
  end

  def index
    base_filter = {
        base_filter_key: 'account_id',
        base_filter_value: params[:account_id]
    }
    authorize_acl :sales_invoice, 'index'
    respond_to do |format|
      format.html { }
      format.json do
        service = Services::Overseers::Finders::SalesInvoices.new(params.merge(base_filter), current_overseer)
        service.call
        @indexed_sales_invoices = service.indexed_records
        @sales_invoices = service.records
      end
    end
  end
end

app/controllers/overseers/accounts_controller.rb
class Overseers::AccountsController < Overseers::BaseController
  before_action :set_account, only: [:edit, :update, :show]


  def index
    @accounts = ApplyDatatableParams.to(Account.all, params)
    authorize_acl @accounts
  end

  def show
    if @account.is_customer?
      service = ['Services', 'Overseers', 'Reports', 'Account'].join('::').constantize.send(:new, @account, params)
      @data = service.call
    end

    authorize_acl @account
  end

  def autocomplete
    @accounts = ApplyParams.to(Account.all, params)
    authorize_acl @accounts
  end

  def autocomplete_supplier
    @accounts = ApplyParams.to(Account.all.where(account_type: 'is_supplier'), params)
    authorize_acl @accounts
  end

  def new
    @account = Account.new(overseer: current_overseer)
    authorize_acl @account
  end

  def create
    @account = Account.new(account_params.merge(overseer: current_overseer))
    authorize_acl @account

    if @account.alias.blank?
      @account.alias = @account.name
    end

    if @account.save_and_sync
      @account.update_attributes(remote_uid: @account.id)
      redirect_to overseers_account_path(@account), notice: flash_message(@account, action_name)
    else
      render 'new'
    end
  end

  def edit
    authorize_acl @account
  end

  def update
    @account.assign_attributes(account_params.merge(overseer: current_overseer))
    authorize_acl @account

    if @account.alias.blank?
      @account.alias = @account.name
    end

    if @account.save_and_sync
      redirect_to overseers_account_path(@account), notice: flash_message(@account, action_name)
    else
      render 'edit'
    end
  end

  def payment_collections
    @accounts = ApplyDatatableParams.to(Account.all.order(:name), params)
    authorize_acl :account
    service = Services::Overseers::SalesInvoices::PaymentDashboard.new()
    service.call
    @summery_data = service.summery_data
  end

  def ageing_report
    @accounts = ApplyDatatableParams.to(Account.all.order(:name), params)
    authorize_acl :account
    service = Services::Overseers::SalesInvoices::AgeingReport.new()
    service.call
    @summery_data = service.summery_data
  end

  private

    def account_params
      params.require(:account).permit(
        :name,
          :alias,
          :logo,
          :account_type
      )
    end

    def set_account
      @account = Account.find(params[:id])
    end
end

app/controllers/overseers/activities/base_controller.rb
class Overseers::Activities::BaseController < Overseers::BaseController
  before_action :activity

  private
    def activity
      @activity = Activity.find(params[:activity_id])
    end
end

app/views/overseers/review_questions/_form.html.erb
<div class="col-lg-12">
  <div class="page-header">
    <h2><%= action_name.capitalize %> Review Question</h2>
    <!-- <p>This will <em>'<%= submit_text(@review_question).downcase %>'</em> and log it under
      <strong><%= current_overseer.full_name %></strong>.</p> -->
  </div>
  <%= simple_form_for([:overseers, @review_question], :html => {:class => 'needs-validation', :'novalidate' => '', :'data-parsley-validate' => ''}) do |f| %>
    <%= render 'shared/snippets/form_errors', f: f %>
    <div class="bmro-card bmro-card-padding">
      <div class="form-group">
        <%= f.input :question, :placeholder => 'e.g. Product Technical Expertise', :required => 'true',  input_html: { class: 'bmro-form-input bmro-bg' },:class => 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.input :weightage, :placeholder => 'e.g. 30', :required => 'true', input_html: { class: 'bmro-form-input bmro-bg' }, :class => 'form-control' %>
      </div>

  <!--    <div class="form-group">-->
        <%#= f.input :rating, :placeholder => '', :required => 'true', :class => 'form-control' %>
  <!--    </div>-->

      <div class="form-group">
        <%= f.input :question_type, :wrapper => :custom_multi_select, input_html: { class: 'bmro-form-input bmro-dropdown-icon bmro-bg' }, as: :select, include_blank: "Select Review Question Type",collection: enum_to_collection(ReviewQuestion.question_types) %>
      </div>

      <div class="mt-3">
        <% if action_name.capitalize == "New" %>
          <%= button_tag(type: "submit", class: "btn btn-success btn-block bmro-button") do %>
            <i class="fal fa-plus-circle"></i> Create Review Question
          <% end %>
        <% else %>
          <%= button_tag(type: "submit", class: "btn btn-warning btn-block mb-2 bmro-button") do %>
            <i class="fal fa-pen"></i> Update Review Question
          <% end %>
        <% end %>
      </div>
    </div> 
  <% end %>
</div>

app/views/overseers/review_questions/edit.html.erb
<%= render 'overseers/review_questions/form' %>

app/views/overseers/review_questions/index.html.erb
<% provide :container_fluid, true %>
<% provide :can_be_directly_created, true %>
<% provide :can_be_ajaxed, true %>

<% content_for :notice_message do %>
  <ul class="list-group text-primary mb-3">
  <% if ReviewQuestion.overall_weightage('Sales').to_i != 100 %>
      <li class="list-group-item">
        <i class="fal fa-exclamation-triangle mr-2"></i>Overall weightage of Sales Type Questions is <%= ReviewQuestion.overall_weightage('Sales').to_i %>, it should always be 100.
      </li>
  <% end %>
  <% if ReviewQuestion.overall_weightage('Logistics').to_i != 100 %>
      <li class="list-group-item">
        <i class="fal fa-exclamation-triangle mr-2"></i>Overall weightage of Logistics Type Questions is <%= ReviewQuestion.overall_weightage('Logistics').to_i %>, it should always be 100.
      </li>
  <% end %>
  </ul>
<% end %>

<% content_for :header_row do %>
  <th class="no-sort" width="98px">Quick Actions</th>
  <th class="no-sort text-left">Question</th>
  <th class="no-sort text-left">Type</th>
  <th class="no-sort text-right">Weightage</th>
<% end %>

<div class="col-lg-12">
  <%= render layout: 'shared/layouts/datatable' do %>
  <% end %>
</div>

app/views/overseers/review_questions/new.html.erb
<%= render 'overseers/review_questions/form' %>

app/views/overseers/review_questions/show.html.erb
<div class="col-lg-12">

  <section class="pt-0 pt-lg-0 pb-0">
    <div class="d-md-flex justify-content-between">
      <h3 class="display-5 d-flex align-items-center bmro-form-heading">
        Review Question Show
      </h3>
      <% if is_authorized(@review_question, 'show') %>
        <a href="<%= edit_overseers_review_question_path(@review_question) %>" class="btn btn-warning btn-rounded align-self-center btn-block-sm-down bmro-button"><i class="fal fa-pen mr-1"></i>Edit</a>
      <% end %>
    </div>

    <ul class="list-group text-primary mb-3">
      <% if ReviewQuestion.overall_weightage('Sales').to_i != 100 %>
        <li class="list-group-item">
          <i class="fal fa-exclamation-triangle mr-2"></i>Overall weightage of Sales Type Questions is <%= ReviewQuestion.overall_weightage('Sales').to_i %>, it should always be 100.
        </li>
      <% end %>
      <% if ReviewQuestion.overall_weightage('Logistics').to_i != 100 %>
        <li class="list-group-item">
          <i class="fal fa-exclamation-triangle mr-2"></i>Overall weightage of Sales Type Questions is <%= ReviewQuestion.overall_weightage('Logistics').to_i %>, it should always be 100.
        </li>
      <% end %>
    </ul>

  </section>

  <section class="mb-3">
    <div class="card mb-2">
      <div class="card-body">
        <h6 class="text-uppercase text-black-50 mb-1 bmro-form-heading">Details</h6>
        <div class="form-row">
          <div class="col-12 col-md-12 mb-2">
            <strong class="d-block bmro-summary-heading">Question</strong>
            <div class="bmro-summary-data">
            <%= @review_question.question %>
            </div>
          </div>
        </div>
        <div class="form-row">
          <div class="col-6 col-md-3 mb-2">
            <strong class="d-block bmro-summary-heading">Weightage</strong>
            <div class="bmro-summary-data">
            <%= @review_question.weightage %>
            </div>
          </div>
          <div class="col-6 col-md-3 mb-2">
            <strong class="d-block bmro-summary-heading">Question Type</strong>
            <div class="bmro-summary-data">
            <%= @review_question.question_type %>
            </div>
          </div>
        </div>
      </div>
    </div>

  </section>

</div>