config/routes.rb
  namespace :suppliers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'suppliers/sessions', passwords: 'suppliers/passwords'}, path: :suppliers
  end

  resources :trainings, only: %i[index show] do
    get :search, on: :collection
  end

  namespace :customers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords'}, path: :customers
  end

  namespace :api do
    namespace :v1 do
      resources :punchouts do
        collection do
          post 'auth'
        end
      end
    end
  end

  namespace 'callbacks' do
    resources :sales_orders do
      member do
        patch 'update'
      end
    end

    resources :sales_invoices do
      member do
        patch 'update'
      end
    end

    resources :sales_receipts

    resources :sales_shipments do
      member do
        patch 'update'
      end
    end

    resources :credit_notes do
      member do
        patch 'update'
      end
    end

    post '1de9b0a30075ae8c303eb420c103c320', to: 'image_readers#update'
    resources :purchase_orders
    resources :products

    get 'login' => '/callbacks/sessions#new'
  end

  namespace 'overseers' do
    resources :customer_feedbacks, only: :index 

    get '/docs/*page' => 'docs#index'
    resources :delivery_challans do
      collection do
        get 'next_step'
      end

      member do
        get 'preview'
        get 'relationship_map'
        get 'get_relationship_map_json'
      end
    end
    resources :payment_collection_emails
    resources :attachments
    resources :review_questions
    resources :banks
    resources :ifsc_codes do
      collection do
        get 'suggestion'
      end
    end

    resource :dashboard, controller: :dashboard do
      get 'chewy'
      get 'reset_index'
      get 'serializer'
      get 'migrations'
      get 'console'
      get 'get_status_records'
      get 'show_email_message_modal'
      post 'update_inquiry'
      post 'update_invoice_request'
      post 'approve_reject_so'
      get 'get_filtered_inquiries'
      get 'get_inquiry_tasks'
      get 'follow_up_dashboard'
      get 'sales_manager'
      get 'accounts'
      get 'sales_executive'
      get 'my_team'
      get 'get_recent_inquiries'
      get 'get_account_executive_data'
    end

    resources :tasks do
      member do
        get 'render_modal_form'
        patch 'add_comment'
      end
      scope module: 'tasks' do
        resources :comments
      end
    end

    resources :remote_requests do
      member do
        get 'show'
      end
      collection do
        get 'resend_failed_requests'
      end
    end

    resources :resync_remote_requests do
      member do
        get 'resend_failed_request'
      end
      collection do
        get 'all_requests'
      end
    end

    resources :callback_requests do
      member do
        get 'show'
      end
    end

    resources :document_creations

    resources :acl_resources do
      collection do
        get 'resource_json'
        get 'menu_resource_json'
      end
    end

    resources :notifications do
      collection do
        post 'mark_as_read'
        get 'queue'
      end
    end

    # resources :reports
    resources :reports do
      member do
        get 'export_report'
      end
    end
    resources :company_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :contact_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :activities, except: [:show] do
      collection do
        get 'pending'
        post 'approve_selected'
        post 'reject_selected'
        post 'add_to_inquiry'
        get 'export_all'
        get 'export_filtered_records'
      end
      member do
        get 'approve'
        get 'reject'
      end
      scope module: 'activities' do
        resources :email_messages do
          collection do
            get 'minutes_of_meeting'
            post 'minutes_of_meeting_notification'
            get 'follow_up_email'
            post 'follow_up_email_notification'
          end
        end
      end
    end

    resource :profile, controller: :profile, except: [:show, :index]
    resources :overseers do
      member do
        patch 'save_acl_resources'
        get 'get_resources'
        get 'get_menu_resources'
        get 'edit_acl'
        patch 'update_acl'
        get 'change_password'
        patch 'update_password'
        get 'becomes'
      end

      collection do
        get 'get_resources'
        get 'isp_report'
        get 'export_isp_report'
      end
    end


    resources :acl_roles do
      member do
        get 'get_acl'
        get 'get_acl_menu'
        get 'get_role_resources'
        post 'save_role'
      end
      collection do
        get 'get_default_resources'
      end
    end

    resources :annual_targets

    resources :exports, except: [:show] do
      collection do
        get 'generate_export'
      end
    end

    resources :suppliers do
      collection do
        get 'customized_index'
        get 'autocomplete'
        get 'export_all'
        get 'export_filtered_records'
      end
    end

    resources :contacts do
      collection do
        get 'autocomplete'
        get 'fetch_company_account'
      end

      member do
        get 'become'
      end
    end

    resources :sales_quotes do
    end

    resources :brands do
      collection do
        get 'autocomplete'
      end
    end

    resources :measurement_units, except: [:show] do
      collection do
        get 'autocomplete'
      end
    end

    resources :tax_codes, except: [:show] do
      collection do
        get 'autocomplete'
        get 'autocomplete_for_product'
      end
    end

    resources :addresses do
      collection do
        get 'autocomplete'
        get 'warehouse_addresses'
        get 'is_sez_params'
        get 'get_gst_code'
      end
    end

    resources :categories do
      collection do
        get 'autocomplete'
        get 'autocomplete_closure_tree'
        get 'export_all'
        get 'autocomplete_active'
      end
    end

    resources :products do
      collection do
        get 'autocomplete'
        get 'non_kit_autocomplete'
        get 'service_autocomplete'
        get 'autocomplete_mpn'
        get 'suggestion'
      end
      member do
        get 'customer_bp_catalog'
        get 'best_prices_and_supplier_bp_catalog'
        get 'sku_purchase_history'
        get 'resync'
        get 'resync_inventory'
        get 'autocomplete_suppliers'
        get 'get_product_details'
      end

      collection do
        get 'autocomplete'
        get 'pending'
        get 'export_all'
        get 'export_filtered_records'
        resources :product_imports, only: [:new, :create] do
          collection do
            get 'excel_template'
          end
        end
      end

      scope module: 'products' do
        resources :comments
      end
    end

    resources :kits do
      member do
      end

      collection do
        get 'autocomplete'
      end
    end

    resources :po_requests do
      member do
        get 'new_purchase_order'
        post 'create_purchase_order'
        get 'manager_amended'
      end
      collection do
        get 'product_resync_inventory'
      end
      scope module: 'po_requests' do
        resources :payment_requests
        resources :email_messages do
          collection do
            get 'sending_po_to_supplier'
            post 'sending_po_to_supplier_notification'
            get 'dispatch_from_supplier_delayed'
            post 'dispatch_from_supplier_delayed_notification'
            get 'material_received_in_bm_warehouse'
            post 'material_received_in_bm_warehouse_notification'
          end
        end
      end

      collection do
        get 'autocomplete'
        get 'pending_and_rejected'
        get 'cancelled'
        get 'under_amend'
        get 'amended'
        get 'pending_stock_approval'
        get 'stock_amend_requests'
        get 'stock'
        get 'completed_stock'
        get 'add_comment'
      end
      member do
        get 'render_modal_form'
        get 'render_cancellation_form'
        get 'reject_purchase_order_modal'
        patch 'rejected_purchase_order'
        patch 'cancel_porequest'
        get 'render_comment_form'
        patch 'add_comment'
      end
    end

    resources :invoice_requests do
      collection do
        get 'autocomplete'
        get 'pending'
        get 'completed'
        get 'cancelled'
      end
      member do
        get 'render_modal_form'
        patch 'cancel_invoice_request'
        patch 'add_comment'
      end
    end

    resources :ar_invoice_requests do
      collection do
        get 'pending'
        get 'completed'
        get 'cancelled'
      end
      member do
        get 'render_cancellation_form'
        get 'download_eway_bill_format'
        patch 'cancel_ar_invoice'
        get 'render_modal_form'
        patch 'add_comment'
      end
    end

    resources :outward_dispatches do
      collection do
        get 'create_with_packing_slip'
      end
      member do
        get 'make_packing_zip'
        get 'render_modal_form'
        patch 'add_comment'
      end
      scope module: 'outward_dispatches' do
        resources :packing_slips do
          collection do
            get 'add_packing'
            post 'submit_packing'
            get 'edit_outward_packing_slips'
          end
        end
        resources :email_messages do
          collection do
            get 'dispatch_mail_to_customer'
            post 'dispatch_mail_to_customer_notification'
          end
        end
      end
    end



    resources :sales_orders do

app/controllers/customers/companies/addresses_controller.rb
class Customers::Companies::AddressesController < Customers::Companies::BaseController

  def autocomplete
    @addresses = ApplyParams.to(@company.addresses.includes(:state), params)
    authorize @addresses
  end

  def customer_po_autocomplete
    authorize :checkout
    @customer_pos = ApplyParamsToArray.to(Inquiry.where(company_id: @company.id).where.not(customer_po_number: "").map(&:customer_po_number)&.uniq&.compact, params)
  end

end

app/controllers/customers/companies/base_controller.rb
class Customers::Companies::BaseController < Customers::BaseController
  before_action :set_company

  private
    def set_company
      @company = Company.find(params[:company_id])
    end
end

app/controllers/customers/companies_controller.rb
# frozen_string_literal: true

class Customers::CompaniesController < Customers::BaseController
  def choose_company
    @contact = current_customers_contact
    if @contact.companies.size <= 1
      session[:current_company_id] = @contact.companies.first.id
      redirect_to customers_dashboard_path
    else
      render 'shared/layouts/choose_company'
    end
    authorize @contact
  end

  def contact_companies
    @companies = ApplyParams.to(current_customers_contact.companies, params)
    authorize @companies
  end
end

app/controllers/customers/customer_products_controller.rb
class Customers::CustomerProductsController < Customers::BaseController
  before_action :set_customer_product, only: [:show, :to_cart]
  before_action :set_view, only: :index
  before_action :set_data_for_saint_gobain, :set_data_for_henkel, only: [:index, :show]
  include DisplayHelper

  def index
    authorize :customer_product

    if @view == 'grid'
      params[:per] = 24
    end

    params[:page] = 1 unless params[:page].present?

    account = Account.find(2431)
    service = Services::Customers::Finders::CustomerProducts.new(params.merge(published: true), current_customers_contact, current_company, sort_by: sort_by, sort_order: 'desc')
    service.call
    @indexed_customer_products = service.indexed_records
    @customer_products = service.records.with_eager_loaded_images.try(:reverse)
    # for henkel company specific changes
    @is_henkel = (current_company.account == account)

    @default_quantity = nil
    if @is_henkel
      @default_quantity = 0
    end

    @customer_products_paginate = @indexed_customer_products.page(params[:page]) if params[:page].present?
  end

  def autocomplete
    service = Services::Overseers::Finders::CustomerProducts.new(params.merge(page: 1))
    service.call

    @indexed_customer_products = service.indexed_records
    @customer_products = service.records
    authorize @customer_products
  end

  def show
    authorize @customer_product
    @account = Account.find(2431)
    @default_quantity = @customer_product.moq
    # for henkel company specific changes
    @is_henkel = (current_company.account == @account)
    @display_class = ''
    if @is_henkel
      @default_quantity = 0
      @display_class = get_instock_status(@customer_product, @phursungi_warehouse) ? '' : 'd-none'
    end

    if @is_saint_gobain
      @display_class = get_instock_status(@customer_product, [@bhiwandi_warehouse, @chennai_warehouse]) ? '' : 'd-none'
    end
  end

  def most_ordered_products
    authorize :customer_product

    skip_skus = ['BM9L3P1', 'BM9C4L6']
    skip_product_ids = Product.where('sku ILIKE ANY ( array[?] )', skip_skus).uniq.pluck(:id)

    products = Inquiry.joins(:inquiry_products).where(company: current_company).top(:product_id, 55).reject{ |op, count| op.in?(skip_product_ids) } # nil top returns all
    @total_products = products.size
    @most_ordered_products = products.drop(5).map { |id, c| [Product.find(id), [c, 'times'].join(' ')] }
  end

  def product_details
    authorize :customer_product
    @product = Product.find(params[:id])
    product_details = {}
    product_details['brand'] = @product.brand.to_s
    product_details['tax_code_id'] = @product.best_tax_code.id
    product_details['tax_rate_id'] = @product.best_tax_rate.id
    product_details['measurement_unit'] = @product.measurement_unit.to_s
    product_details['converted_unit_selling_price'] = @product.latest_unit_cost_price
    product_details['mpn'] = @product.mpn
    product_details['category'] = @product.category.to_s
    render json: product_details
  end


  private

    def set_view
      # @view = @current_company.grid_view? ? 'grid' : 'list'
      @view = if params[:view].present? && params[:view] == 'grid'
        'grid'
      else
        'list'
      end
    end

    def sort_by
      case params[:sort]
      when 'inquiries'
        'inquiries'
      when 'qty_in_stock_desc'
        'qty_in_stock'
      else
        'created_at'
      end
    end

    def set_customer_product
      @customer_product ||= CustomerProduct.find(params[:id])
    end

    def set_data_for_saint_gobain
      authorize :customer_product
      @is_saint_gobain = (current_company.id == 11420)
      @bhiwandi_warehouse = Warehouse.find 'LGVfay'
      @chennai_warehouse = Warehouse.find 'OxGf6R'
    end

    def set_data_for_henkel
      authorize :customer_product
      @phursungi_warehouse = Warehouse.find 'rQJfAO'
    end
end

app/controllers/overseers/companies/base_controller.rb
class Overseers::Companies::BaseController < Overseers::BaseController
  before_action :set_company

  private
    def set_company
      @company = Company.find(params[:company_id])
    end
end

app/controllers/overseers/companies/company_reviews_controller.rb
class Overseers::Companies::CompanyReviewsController < Overseers::Companies::BaseController
  def index
    # 8082
    base_filter = {
        base_filter_key: 'company_id',
        base_filter_value: params[:company_id]
    }
    authorize_acl :company_review
    respond_to do |format|
      format.html { }
      format.json do
        service = Services::Overseers::Finders::CompanyReviews.new(params.merge(base_filter), current_overseer)
        service.call
        @indexed_company_reviews = service.indexed_records
        @company_reviews = service.records
      end
    end
  end
end

app/controllers/overseers/companies/contacts_controller.rb
# frozen_string_literal: true

class Overseers::Companies::ContactsController < Overseers::Companies::BaseController
  def autocomplete
    @contacts = ApplyParams.to(@company.contacts, params)
    authorize_acl @contacts
  end
end

app/controllers/overseers/companies/customer_orders_controller.rb
class Overseers::Companies::CustomerOrdersController < Overseers::Companies::BaseController
  def index
    @customer_orders = ApplyDatatableParams.to(@company.customer_orders, params.reject! { |k, v| k == 'company_id' })
    # puts @customer_orders.size
    authorize_acl @customer_orders

    render 'overseers/customer_orders/index'
  end
end

app/controllers/overseers/companies/products_controller.rb
class Overseers::Companies::ProductsController < Overseers::Companies::BaseController
  def index
    base_filter = {
        base_filter_key: 'id',
        base_filter_value: Product.joins(:inquiry_products, :inquiry_product_suppliers).where(inquiry_product_suppliers: { supplier_id: params[:company_id] }).pluck(:id)
    }

    service = Services::Overseers::Finders::Products.new(params.merge(base_filter))
    service.call
    @products = service.records
    @indexed_products = service.indexed_records
    authorize_acl @products
  end
end

app/views/overseers/companies/customer_products/_form.html.erb
<div class="col-lg-12">
  <%= render 'shared/snippets/page_header', e: @customer_product %>

  <%= simple_form_for([:overseers, @company, @customer_product], :html => {:class => 'needs-validation', :'novalidate' => '', :'data-parsley-validate' => ''}) do |f| %>
    <%= render 'shared/snippets/form_errors', f: f %>
    <%= f.hidden_field :company_id %>
    <div class="bmro-card bmro-card-padding">
    <div class="form-row">
       
     <div class="col-12 col-md-12">
       <%= f.label :published %>
       <%= f.check_box :published, data: {toggle: "toggle" } %>
     </div>

      <div class="col-6 col-md-6">
        <%= f.input :company, as: :string, disabled: true %>
      </div>
      <div class="col-6 col-md-6">
        <%= f.association :product, collection: [f.object.product], include_blank: "Type SKU number, name, or brand", label_method: :to_s, input_html: {class: 'select2-ajax', :'data-source' => autocomplete_overseers_products_path, :'data-parsley-errors-messages-disabled' => '', :'data-parsely-no-valid-feedback' => ''} %>
      </div>
      <div class="col-12">
        <%= f.input :name, required: false %>
      </div>
      <div class="col-12">
        <%= f.input :technical_description, label: 'Technical Description', required: false %>
      </div>
      <hr/>
      <div class="col-6">
        <%= f.input :sku, label: 'Material code', required: false %>
      </div>
      <div class="col-6">
        <%= f.input :customer_product_sku, label: "Customer's Material Code", required: false %>
      </div>
      <hr/>
      <div class="col-6 col-md-4">
        <%= f.association :measurement_unit, collection: MeasurementUnit.new_uom, wrapper: :custom_multi_select, include_blank: false %>
      </div>
      <div class="col-6 col-md-4">
        <%= f.input :moq, label: 'MoQ' %>
      </div>
      <div class="col-6 col-md-4">
        <%= f.input :customer_uom, label: "Customer's UOM" %>
      </div>
      <div class="col-6 col-md-4">
        <%= f.input :lead_time, label: "Lead Time (Days)" %>
      </div>
      <hr/>
      <div class="col-6 col-md-4">
        <%= f.input :customer_price, label: 'Price' %>
      </div>
      <div class="col-6 col-md-4">
        <%= f.association :tax_code, collection: selected_option_or_nil(f, :tax_code), label_method: :to_s, include_blank: "Type to search", input_html: {class: 'select2-ajax', :'data-source' => autocomplete_for_product_overseers_tax_codes_path(product_id: ( f.object.product.present? ? f.object.product.id : nil))} %>
      </div>
      <div class="col-6 col-md-4">
        <%= f.association :tax_rate, wrapper: :custom_multi_select, collection: TaxRate.all.map {|tax_rate| [tax_rate.to_s, tax_rate.id, {'data-tax_rate' => tax_rate.tax_percentage}]}, input_html: {"data-bind": ""} %>
      </div>
      
    </div>

    <div class="form-row">
      <div class="col-12">
        <%= f.association :brand, collection: selected_option_or_nil(f, :brand), include_blank: 'Select a brand', input_html: {class: 'select2-ajax', :'data-source' => autocomplete_overseers_brands_path} %>
      </div>
      <div class="form-row">
        <div class="col-12">
            <%= f.association :category, collection: selected_option_or_nil(f, :category), include_blank: 'Select a Categories', :multiple => true, input_html: {class: 'select2-ajax', :'data-source' => autocomplete_overseers_categories_path} %>
        </div>
      </div>
      <div class="col-12 col-md-12 ">
        <div class="d-block d-md-flex align-items-end">
          <div class="flex-grow-1">
            <%= f.input :images, wrapper: :custom_file, input_html: {multiple: true}, label: 'Product images' %>
          </div>
          <div class="form-group">
            <% f.object.images.each do |image| %>
              <%= link_to url_for(image), class: 'ml-md-1 btn btn-success', target: '_blank', :"data-toggle" => 'tooltip', :status => image.filename do %>
                <i class="fal fa-download"></i>
                <%= link_to overseers_attachment_path(image.id), class: 'btn btn-outline-danger btn-sm ml-1 mr-1 mr-md-0', method: :delete, data: {confirm: 'Are you sure?'}, :"data-toggle" => 'tooltip', :status => ['Delete', ' ', image.filename, '?'].join('') do %>
                  <i class="fal fa-trash-alt"></i>
                <% end if image.present? && is_authorized(:attachment, 'destroy') %>
              <% end %>
            <% end if f.object.images.attached? %>
          </div>
        </div>
      </div>
    </div>
      <div class="form-row">
      <div class="col-12">
    <div class="bmro-button-parent bmro-card-footer">
    <%= action_button(action_name, @customer_product) %>
    </div>
      </div>
      </div>
  <% end %>
</div>
</div>

app/views/overseers/companies/customer_products/_tab_index.html.erb
<div class="tab-pane fade active show" id="products" role="tabpanel">
  <% content_for :ajax_url, flush: true do %><%= overseers_company_customer_products_path(company) %>
  <% end %>
  <% content_for :header_row, flush: true do %>
    <th class="no-sort" width="98px">Quick Actions</th>
    <th class="no-sort">Name</th>
    <th class="no-sort">SKU</th>
    <th class="no-sort desktop">Customer Price</th>
    <th class="no-sort desktop">SAP Status</th>
    <th class="sort desktop" data-name = "image">Image Attached</th>
    <th class="sort desktop text-right" data-name="product_created_at">Created</th>
  <% end %>

  <% content_for :heading_buttons_internal_datatable, flush: true do %>
    <div>
      <%= link_to (company.grid_view?? 'List View' : 'Grid View'), toggle_view_overseers_company_customer_products_url(company), class: "btn align-self-center btn-block-sm-down mb-2 mb-md-0 mr-1 bmro-button", method: :post, title: "Changes the customer products to #{(company.grid_view?? 'list view' : 'grid view')}" %>
      <a href="<%= new_overseers_company_product_image_path(company)%>" class="btn btn-success btn-rounded align-self-center btn-block-sm-down mb-2 mb-md-0 mr-1 bmro-button"><i class="bmro-plus-icon"></i>Upload images</a>
      <% if is_authorized(:customer_product, 'generate_catalog') %>
        <a href="<%= generate_catalog_overseers_company_customer_products_path(company) %>" data-method="post" class="btn btn-success btn-rounded align-self-center btn-block-sm-down mb-2 mb-md-0 mr-1 bmro-button" ><i class="fal fa-plus-circle mr-1"></i>Generate
          Catalog</a>
      <% end %>
      <% if is_authorized(:customer_product, 'destroy_all') %>
        <a href="<%= destroy_all_overseers_company_customer_products_path(company) %>" data-method="post" class="btn btn-danger btn-rounded align-self-center btn-block-sm-down mb-2 mb-md-0 mr-1 bmro-button"><i class="fal fa-minus-circle mr-1"></i>Destroy
          Catalog</a>
      <% end %>
      <% if is_authorized(:customer_product, 'new') %>
        <a href="<%= new_overseers_company_customer_product_path(company) %>" class="btn btn-success btn-rounded align-self-center btn-block-sm-down mb-2 mb-md-0 mr-1 bmro-button"><i class="fal fa-plus-circle mr-1"></i>New
          Customer Product</a>
      <% end %>
      <a href="<%= new_excel_customer_product_import_overseers_company_imports_path(company) %>" class="btn btn-success btn-rounded align-self-center btn-block-sm-down mb-2 mb-md-0 bmro-button"><i class="fal fa-file-excel mr-1"></i>Add
        products using excel</a>
      <% if company.customer_products.count > 0 && is_authorized(:customer_product, 'export_customer_product') %>
        <a href="<%= export_customer_product_overseers_company_customer_products_path(company, format: :csv) %>" class="btn btn-success btn-rounded align-self-center btn-block-sm-down mb-2 mb-md-0 bmro-button"><i class="fal fa-download mr-1"></i>Company Product Export</a>
      <% end %>
    </div>
  <% end %>
  <%= render 'shared/layouts/internal_datatable', entity: company, children: 'products' %>
</div>

app/views/overseers/companies/customer_products/edit.html.erb
<%= render 'overseers/companies/customer_products/form' %>

app/views/overseers/companies/customer_products/new.html.erb
<%= render 'overseers/companies/customer_products/form' %>

app/views/overseers/companies/customer_products/show.html.erb
<div class="col-lg-12">
  <section class="pt-3 pt-lg-4 pb-2">
    <div class="d-md-flex justify-content-between">
      <h3 class="display-5 d-flex align-items-center">
        <%= @customer_product.name %>
      </h3>
      <% if is_authorized(@customer_product, 'edit') %>
        <a href="<%= edit_overseers_company_customer_product_path(@company) %>" class="btn btn-success btn-rounded align-self-center btn-block-sm-down mb-2 mb-md-0 bmro-button"><i class="fal fa-pen mr-1"></i>Edit
          customer_product</a>
      <% end %>
    </div>
  </section>

  <section class="mb-3">
    <div class="card">
      <div class="card-body">
        <div>
          <h6 class="text-uppercase text-black-50 mb-1">customer_product Details</h6>
          <div class="form-row">

            <% if @customer_product.company.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Company Name</strong>
                <%= @customer_product.company.name %>
              </div>
            <% end %>

            <% if @customer_product.name.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Name</strong>
                <%= @customer_product.name %>
              </div>
            <% end %>

            <% if @customer_product.technical_description.present? %>
              <div class="col-12 mb-2">
                <strong class="d-block">Technical Description</strong>
                <%= @customer_product&.technical_description %>
              </div>
            <% end %>

            <% if @customer_product.sku? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">BM Number</strong>
                <%= @customer_product.sku %>
              </div>
            <% end %>

            <% if @customer_product.customer_product_sku.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Customer's Material Code </strong>
                <%= @customer_product&.customer_product_sku %>
              </div>
            <% end %>

            <% if @customer_product.customer_price? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Customer Price</strong>
                <%= format_currency(@customer_product.customer_price) %>
              </div>
            <% end %>

            <% if @customer_product.moq? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Minimum Ordered Quantity</strong>
                <%= @customer_product.moq %>
              </div>
            <% end %>

            <% if @customer_product.lead_time.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Lead Time (Days)</strong>
                <%= @customer_product.lead_time %>
              </div>
            <% end %>

            <% if @customer_product.tax_code.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Tax Code</strong>
                <%= @customer_product.tax_code.code %>
              </div>
            <% end %>

            <% if @customer_product.tax_rate.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Tax Rate</strong>
                <%= @customer_product.tax_rate.tax_percentage %>
              </div>
            <% end %>

            <% if @customer_product.measurement_unit.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Measurement Unit</strong>
                <%= @customer_product.measurement_unit.name %>
              </div>
            <% end %>

            <% if @customer_product.customer_uom.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Customer's UOM</strong>
                <%= @customer_product.customer_uom %>
              </div>
            <% end %>

            <% if @customer_product.brand.present? %>
              <div class="col-6 col-md-3 mb-2">
                <strong class="d-block">Brand</strong>
                <%= @customer_product.brand %>
              </div>
            <% end %>

            <div class="col-6 col-md-3 mb-2">              
              <strong class="d-block bmro-summary-heading">Published</strong>
              <div class="bmro-summary-data">
                <%= format_boolean(@customer_product.published?) %>
              </div> 
            </div>
          </div>
        </div>
      </div>
    </div>
  </section>
</div>