config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/pro/web'
  post '/rate' => 'rater#create', :as => 'rate'
  get '/faq', to: 'static_pages#faq'
  mount Maily::Engine, at: '/maily' if Rails.env.development?
  mount ActionCable.server, at: '/cable'
  authenticate :overseer, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: 'overseers/inquiries#index'
  get '/overseers', to: redirect('/overseers/dashboard'), as: 'overseer_root'
  get '/customers', to: redirect('/customers/dashboard'), as: 'customer_root'
  get '/suppliers', to: redirect('/suppliers/dashboard'), as: 'supplier_root'

  get '/release_notes', to: 'overseers/site_updates#show'
  post '/release_notes', to: 'overseers/site_updates#create'

  devise_for :overseers, controllers: {sessions: 'overseers/sessions', omniauth_callbacks: 'overseers/omniauth_callbacks'}
  # devise_for :contacts, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords'}, path: :customers

  namespace :suppliers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'suppliers/sessions', passwords: 'suppliers/passwords'}, path: :suppliers
  end

  resources :trainings, only: %i[index show] do
    get :search, on: :collection
  end

  namespace :customers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords'}, path: :customers
  end

  namespace :api do
    namespace :v1 do
      resources :punchouts do
        collection do
          post 'auth'
        end
      end
    end
  end

  namespace 'callbacks' do
    resources :sales_orders do
      member do
        patch 'update'
      end
    end

    resources :sales_invoices do
      member do
        patch 'update'
      end
    end

    resources :sales_receipts

    resources :sales_shipments do
      member do
        patch 'update'
      end
    end

    resources :credit_notes do
      member do
        patch 'update'
      end
    end

    post '1de9b0a30075ae8c303eb420c103c320', to: 'image_readers#update'
    resources :purchase_orders
    resources :products

    get 'login' => '/callbacks/sessions#new'
  end

  namespace 'overseers' do
    resources :customer_feedbacks, only: :index 

    get '/docs/*page' => 'docs#index'
    resources :delivery_challans do
      collection do
        get 'next_step'
      end

      member do
        get 'preview'
        get 'relationship_map'
        get 'get_relationship_map_json'
      end
    end
    resources :payment_collection_emails
    resources :attachments
    resources :review_questions
    resources :banks
    resources :ifsc_codes do
      collection do
        get 'suggestion'
      end
    end

    resource :dashboard, controller: :dashboard do
      get 'chewy'
      get 'reset_index'
      get 'serializer'
      get 'migrations'
      get 'console'
      get 'get_status_records'
      get 'show_email_message_modal'
      post 'update_inquiry'
      post 'update_invoice_request'
      post 'approve_reject_so'
      get 'get_filtered_inquiries'
      get 'get_inquiry_tasks'
      get 'follow_up_dashboard'
      get 'sales_manager'
      get 'accounts'
      get 'sales_executive'
      get 'my_team'
      get 'get_recent_inquiries'
      get 'get_account_executive_data'
    end

    resources :tasks do
      member do
        get 'render_modal_form'
        patch 'add_comment'
      end
      scope module: 'tasks' do
        resources :comments
      end
    end

    resources :remote_requests do
      member do
        get 'show'
      end
      collection do
        get 'resend_failed_requests'
      end
    end

    resources :resync_remote_requests do
      member do
        get 'resend_failed_request'
      end
      collection do
        get 'all_requests'
      end
    end

    resources :callback_requests do
      member do
        get 'show'
      end
    end

    resources :document_creations

    resources :acl_resources do
      collection do
        get 'resource_json'
        get 'menu_resource_json'
      end
    end

    resources :notifications do
      collection do
        post 'mark_as_read'
        get 'queue'
      end
    end

    # resources :reports
    resources :reports do
      member do
        get 'export_report'
      end
    end
    resources :company_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :contact_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :activities, except: [:show] do
      collection do
        get 'pending'
        post 'approve_selected'
        post 'reject_selected'
        post 'add_to_inquiry'
        get 'export_all'
        get 'export_filtered_records'
      end
      member do
        get 'approve'
        get 'reject'
      end
      scope module: 'activities' do
        resources :email_messages do
          collection do
            get 'minutes_of_meeting'
            post 'minutes_of_meeting_notification'
            get 'follow_up_email'
            post 'follow_up_email_notification'
          end
        end
      end
    end

    resource :profile, controller: :profile, except: [:show, :index]
    resources :overseers do
      member do
        patch 'save_acl_resources'
        get 'get_resources'
        get 'get_menu_resources'
        get 'edit_acl'
        patch 'update_acl'
        get 'change_password'
        patch 'update_password'
        get 'becomes'
      end

      collection do
        get 'get_resources'
        get 'isp_report'
        get 'export_isp_report'
      end
    end


    resources :acl_roles do
      member do
        get 'get_acl'
        get 'get_acl_menu'
        get 'get_role_resources'
        post 'save_role'
      end
      collection do
        get 'get_default_resources'
      end
    end

    resources :annual_targets

    resources :exports, except: [:show] do
      collection do
        get 'generate_export'
      end
    end

    resources :suppliers do
      collection do
        get 'customized_index'
        get 'autocomplete'
        get 'export_all'
        get 'export_filtered_records'
      end
    end

    resources :contacts do
      collection do
        get 'autocomplete'
        get 'fetch_company_account'
      end

      member do
        get 'become'
      end
    end

    resources :sales_quotes do
    end

    resources :brands do
      collection do
        get 'autocomplete'
      end
    end

    resources :measurement_units, except: [:show] do
      collection do
        get 'autocomplete'
      end
    end

    resources :tax_codes, except: [:show] do
      collection do
        get 'autocomplete'
        get 'autocomplete_for_product'
      end
    end

    resources :addresses do
      collection do
        get 'autocomplete'
        get 'warehouse_addresses'
        get 'is_sez_params'
        get 'get_gst_code'
      end
    end

    resources :categories do
      collection do
        get 'autocomplete'
        get 'autocomplete_closure_tree'
        get 'export_all'
        get 'autocomplete_active'
      end
    end

    resources :products do
      collection do
        get 'autocomplete'
        get 'non_kit_autocomplete'
        get 'service_autocomplete'
        get 'autocomplete_mpn'
        get 'suggestion'
      end
      member do
        get 'customer_bp_catalog'
        get 'best_prices_and_supplier_bp_catalog'
        get 'sku_purchase_history'
        get 'resync'
        get 'resync_inventory'
        get 'autocomplete_suppliers'
        get 'get_product_details'
      end

      collection do
        get 'autocomplete'
        get 'pending'
        get 'export_all'
        get 'export_filtered_records'
        resources :product_imports, only: [:new, :create] do
          collection do
            get 'excel_template'
          end
        end
      end

      scope module: 'products' do
        resources :comments
      end
    end

    resources :kits do
      member do
      end

      collection do
        get 'autocomplete'
      end
    end

    resources :po_requests do
      member do
        get 'new_purchase_order'
        post 'create_purchase_order'
        get 'manager_amended'
      end
      collection do
        get 'product_resync_inventory'
      end
      scope module: 'po_requests' do
        resources :payment_requests
        resources :email_messages do
          collection do
            get 'sending_po_to_supplier'
            post 'sending_po_to_supplier_notification'
            get 'dispatch_from_supplier_delayed'
            post 'dispatch_from_supplier_delayed_notification'
            get 'material_received_in_bm_warehouse'
            post 'material_received_in_bm_warehouse_notification'
          end
        end
      end

      collection do
        get 'autocomplete'
        get 'pending_and_rejected'
        get 'cancelled'
        get 'under_amend'
        get 'amended'
        get 'pending_stock_approval'
        get 'stock_amend_requests'
        get 'stock'
        get 'completed_stock'
        get 'add_comment'
      end
      member do
        get 'render_modal_form'
        get 'render_cancellation_form'
        get 'reject_purchase_order_modal'
        patch 'rejected_purchase_order'
        patch 'cancel_porequest'
        get 'render_comment_form'
        patch 'add_comment'
      end
    end

    resources :invoice_requests do
      collection do
        get 'autocomplete'
        get 'pending'
        get 'completed'
        get 'cancelled'
      end
      member do
        get 'render_modal_form'
        patch 'cancel_invoice_request'
        patch 'add_comment'
      end
    end

    resources :ar_invoice_requests do
      collection do

app/controllers/customers/inquiries/base_controller.rb
# frozen_string_literal: true

class Customers::Inquiries::BaseController < Customers::BaseController
  before_action :set_inquiry

  private

    def set_inquiry
      @inquiry = Inquiry.find(params[:inquiry_id])
    end

    def render_pdf_for(record)
      render(
        pdf: record.filename,
        template: ['shared', 'layouts', 'pdf_templates', record.class.name.pluralize.underscore, 'show'].join('/'),
        layout: 'shared/layouts/pdf_templates/show',
        page_size: 'Legal',
        footer: {
          center: '[page] of [topage]'
        },
        locals: {
          record: record
        }
      )
    end
end

app/controllers/customers/inquiries/comments_controller.rb
class Customers::Inquiries::CommentsController < Customers::Inquiries::BaseController
  def index
    @sales_order = @inquiry.sales_orders.find(params[:sales_order_id]) if params[:sales_order_id].present?
    @comments = if @sales_order.present?
      @inquiry.comments.where(sales_order_id: [nil, @sales_order.id])
    else
      @inquiry.comments.earliest
    end

    authorize @comments
  end

  def create
    @comment = @inquiry.comments.build(inquiry_comment_params.merge(overseer: current_overseer))

    authorize @comment

    if @comment.sales_order.present? && @comment.save
      callback_method = %w(approve reject).detect { |action| params[action] }
      send(callback_method) if callback_method.present? && policy(@comment.sales_order).send([callback_method, '?'].join)
      redirect_to overseers_inquiry_comments_path(@inquiry, sales_order_id: @comment.sales_order.to_param), notice: flash_message(@comment, action_name)
    elsif @comment.save
      redirect_to overseers_inquiry_comments_path(@inquiry), notice: flash_message(@comment, action_name)
    else
      render 'new'
    end
  end

  private

    def inquiry_comment_params
      params.require(:inquiry_comment).permit(
        :message,
          :sales_order_id,
          :show_in_portal
      )
    end

    def approve
      service = Services::Overseers::SalesOrders::ApproveAndSerialize.new(@comment.sales_order, @comment)
      service.call
    end

    def reject
      @comment.sales_order.create_rejection(comment: @comment, overseer: current_overseer)
      @comment.sales_order.update_attributes(status: :'Rejected')
      @comment.sales_order.update_index
    end
end

app/controllers/customers/inquiries/sales_orders_controller.rb
class Customers::Inquiries::SalesOrdersController < Customers::Inquiries::BaseController
  before_action :get_final_sales_orders

  def index
  end

  def show
    @final_sales_order = @final_sales_orders.find(params[:id])
    respond_to do |format|
      format.html { }
      format.pdf do
        render_pdf_for @final_sales_order
      end
    end
  end

  private

    def get_final_sales_orders
      @final_sales_orders = @inquiry.final_sales_orders
    end
end

app/controllers/customers/inquiries/sales_quotes_controller.rb
class Customers::Inquiries::SalesQuotesController < Customers::Inquiries::BaseController
  before_action :set_final_sales_quote

  def index
  end

  def show
    respond_to do |format|
      format.html { }
      format.pdf do
        render_pdf_for @final_sales_quote
      end
    end
  end

  private

    def set_final_sales_quote
      @final_sales_quote = @inquiry.final_sales_quote
    end
end

app/controllers/overseers/customer_orders/inquiries_controller.rb
# frozen_string_literal: true

class Overseers::CustomerOrders::InquiriesController < Overseers::CustomerOrders::BaseController
  def new
    authorize_acl @customer_order, 'can_create_inquiry'
    @inquiry = Services::Overseers::Inquiries::NewFromCustomerOrder.new(@customer_order, current_overseer).call
    redirect_to edit_overseers_inquiry_path(@inquiry), notice: flash_message(@inquiry, action_name)
  end
end

app/controllers/overseers/inquiries/base_controller.rb
class Overseers::Inquiries::BaseController < Overseers::BaseController
  before_action :set_inquiry

  private

    def set_inquiry
      @inquiry = Inquiry.find(params[:inquiry_id])
    end

    def render_pdf_for(record, locals = {})
      locals[:pagination] = locals[:pagination] == false ? locals[:pagination] : true

      # if !locals[:pagination]
      # if locals_variables[:locals][:is_pages_visible]
      #  footer = {
      #      center: '[page] of [topage]'
      #  }
      # else
      #  footer = {}
      # end
      render(
        pdf: record.filename,
        template: ['shared', 'layouts', 'pdf_templates', record.class.name.pluralize.underscore, 'show'].join('/'),
        layout: 'shared/layouts/pdf_templates/show',
        page_size: 'A4',
        background: true,
        footer: locals[:pagination] ? { center: '[page] of [topage]' } : {},
        # show_as_html: true,
        locals: {
            record: record
        }.merge(locals)
             )
    end
end

app/controllers/overseers/inquiries/comments_controller.rb
class Overseers::Inquiries::CommentsController < Overseers::Inquiries::BaseController
  before_action :set_notification, only: [:create]

  def index
    @sales_order = @inquiry.sales_orders.find(params[:sales_order_id]) if params[:sales_order_id].present?
    @comments = if @sales_order.present?
      @inquiry.comments.where(sales_order_id: [@sales_order.id]).latest
      # @inquiry.comments.where(sales_order_id: [nil, @sales_order.id]).latest
    else
      @inquiry.comments.latest
    end

    @internal_comments = @comments.internal_comments.page(params[:internal]).per(10)
    @customer_comments = @comments.customer_comments.page(params[:customer]).per(10)
    authorize_acl @comments
  end

  def create
    @comment = @inquiry.comments.build(inquiry_comment_params.merge(overseer: current_overseer))

    authorize_acl @comment

    if @comment.sales_order.present? && @comment.save
      callback_method = %w(approve reject).detect { |action| params[action] }
      send(callback_method) if callback_method.present? && policy(@comment.sales_order).send([callback_method, '?'].join)
      @notification.send_order_comment(
        @inquiry.inside_sales_owner,
          action_name.to_sym,
          @comment.sales_order,
          overseers_inquiry_comments_path(@inquiry, sales_order_id: @sales_order.to_param, show_to_customer: false),
          callback_method, @inquiry.inquiry_number.to_s, @comment.message
      )
      redirect_to overseers_inquiry_comments_path(@inquiry, sales_order_id: @comment.sales_order.to_param, show_to_customer: inquiry_comment_params[:show_to_customer]), notice: flash_message(@comment, action_name)
    elsif @comment.save
      redirect_to overseers_inquiry_comments_path(@inquiry, show_to_customer: inquiry_comment_params[:show_to_customer]), notice: flash_message(@comment, action_name)
    else
      render 'new'
    end
  end

  private

    def inquiry_comment_params
      params.require(:inquiry_comment).permit(
        :message,
          :sales_order_id,
          :show_to_customer
      )
    end

    def approve
      service = Services::Overseers::SalesOrders::ApproveAndSerialize.new(@comment.sales_order, @comment)
      Services::Overseers::Inquiries::UpdateStatus.new(@comment.sales_order, :order_approved_by_sales_manager).call
      service.call
    end

    def reject
      @comment.sales_order.create_rejection(comment: @comment, overseer: current_overseer)
      @comment.sales_order.update_attributes(status: :'Rejected')
      Services::Overseers::Inquiries::UpdateStatus.new(@comment.sales_order, :order_rejected_by_sales_manager).call
      @comment.sales_order.update_index
    end
end

app/controllers/overseers/inquiries/sales_quotes/base_controller.rb
class Overseers::Inquiries::SalesQuotes::BaseController < Overseers::Inquiries::BaseController
  before_action :set_sales_quote

  private
    def set_sales_quote
      @sales_quote = SalesQuote.find(params[:sales_quote_id])
    end
end

app/views/overseers/inquiries/po_requests/_stock.html.erb
<%= provide :container_fluid, true %>
<div class="col-lg-12">
  <div class="page-header">
    <h2><%= action_name.capitalize %> PO Request&nbsp;</h2>
    <p>This will <em>Create purchase order requests for stock</em> and log it under
      <strong><%= current_overseer.full_name %></strong>.</p>
  </div>

  <%= simple_form_for([:overseers, @inquiry], url: preview_stock_po_request_overseers_inquiries_path, method: :POST, :html => {:class => 'needs-validation', :'novalidate' => '', :'data-parsley-validate' => ''}) do |f| %>
    <%= render 'shared/snippets/form_errors', f: f %>

    <%= f.hidden_field :id %>

    <%= f.simple_fields_for :po_requests, @po_requests, wrapper_tag: :div do |po_request| %>
      <div class="card mb-2">
        <div class="card-body">
          <%= render 'shared/snippets/form_errors', f: po_request %>
          <%= po_request.hidden_field :id %>
          <%= po_request.hidden_field :inquiry, as: :string %>

          <div class="form-row">
            <div class="form-group col-6">
              <strong class="d-block">Inquiry</strong>
              <%= link_to overseers_inquiry_path(po_request.object.inquiry) do %>
                <%= po_request.object.inquiry %>
              <% end %>
            </div>
            <br>
            <div class="form-group col-6">
              <strong class="d-block">Company Name</strong>
              <%= link_to overseers_company_path(po_request.object.inquiry.company) do %>
                <%= po_request.object.inquiry.company %>
              <% end %>
            </div>
            <br>
            <div class="col-md-6">
              <%= po_request.association :requested_by, as: :select, :include_blank => true %>
            </div>
            <div class="col-md-6">
              <%= po_request.association :approved_by, as: :select, :include_blank => true, label: "Request Approved By" %>
            </div>
            <div class="col-md-9">
              <%= po_request.input :reason_to_stock, :include_blank => true, label: "Reason to stock", required: true %>
            </div>
            <div class="col-md-3">
              <%= po_request.input :estimated_date_to_unstock, as: :string, input_html: {:'data-toggle' => 'datepicker', :class => 'supplier-committed-date'}, label: "Estimated date to Unstock", required: true%>
            </div>
          </div>
        </div>
      </div>

      <div class="card col-12">
        <div class="card-body">
          <div class="simple-row">

            <%= render 'overseers/po_requests/rows_form', f: po_request, product_path: autocomplete_overseers_products_path, stock: true, supplier_index: @supplier_index %>

            <%= po_request.add_nested_fields_link :rows, class: 'btn btn-success btn-outline-success btn-block mb-2 mb-md-0 bmro-button', role: 'button' do %>
              <i class="fal fa-plus-circle mr-1"></i>Add a product
            <% end %>
          </div>

        </div>
      </div>
    <% end %>

    <div class="card-footer">
      <% if action_name.capitalize == "New" %>
        <%= button_tag(type: "submit", class: "btn btn-warning btn-block bmro-button") do %>
          <i class="fal fa-pen"></i> Preview PO request
        <% end %>
      <% else %>
        <%= button_tag(type: "submit", class: "btn btn-warning btn-block mb-2 bmro-button") do %>
          <i class="fal fa-pen"></i> Update PO Request
        <% end %>
      <% end %>
  <% end %>
  </div>

</div>
<% if @po_requests.comments.persisted.size > 0 %>
  <div class="card">
    <div class="card-body">
      <div class="flex-fill">
        <h6 class="text-uppercase text-black-50 mb-1">Comments History</h6>
      </div>
      <div class="chats mb-3">
        <% @po_requests.comments.each do |comment| %>
          <% if comment.persisted? %>
            <%= format_comment(comment) %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>
<% end %>
</div>

app/views/overseers/inquiries/po_requests/edit.html.erb
<%= render 'overseers/inquiries/po_requests/form' %>

app/views/overseers/inquiries/po_requests/new.html.erb
<%= render 'overseers/inquiries/po_requests/stock' %>

app/views/overseers/inquiries/po_requests/show.html.erb
<%= provide :container_fluid, true %>
<div class="col-lg-12">
  <section class="pt-0 pt-lg-0 pb-2">
    <div class="d-md-flex justify-content-between">

      <div class="col-7">
        <h3 class="display-5 d-flex align-items-center">
          Stock PO Request for Inquiry <%= format_id(@po_request.inquiry.inquiry_number) %>
          :&nbsp;<%= status_badge(@po_request.stock_status) %>
        </h3>
      </div>

      <% if is_authorized(@po_request,'edit') && policy(@po_request).edit? && @po_request.stock_status != 'Stock Cancelled' %>
        <div class="col-1">
          <a href="<%= edit_overseers_inquiry_po_request_path(@po_request.inquiry, @po_request) %>" class="btn btn-warning btn-rounded bmro-button align-self-center btn-block-sm-down"><i class="fal fa-pen mr-1"></i>Edit</a>
        </div>
      <% end %>

      <% if @po_request.stock_status == 'Supplier Stock PO: Amendment Pending' && @po_request.purchase_order.present? %>
        <div class="col-1">
          <a href="<%= manager_amended_overseers_po_request_path(@po_request, is_stock: 'yes') %>" class="btn btn-success btn-rounded bmro-button align-self-center btn-block-sm-down">Amend PO Request</a>
        </div>
      <% end %>

      <% if is_authorized(@po_request,'new_payment_request') && policy(@po_request).new_payment_request? %>
        <div class="col-1">
          <a href="<%= new_overseers_po_request_payment_request_path(@po_request) %>" class="btn btn-success btn-rounded align-self-center bmro-button btn-block-sm-down"><i class="fal fa-dollar-sign mr-1"></i>Payment
            Request</a>
        </div>
      <% end %>

      <% if @po_request.payment_request.present? && is_authorized(@po_request.payment_request,'show') %>
        <div class="col-2">
          <a href="<%= overseers_payment_request_path(@po_request.payment_request) %>" class="btn btn-success btn-rounded align-self-center bmro-button btn-block-sm-down"><i class="fal fa-dollar-sign mr-1"></i>Payment
            Request</a>
        </div>
      <% end %>

    </div>
  </section>

  <section class="mb-3">
    <%= render 'overseers/po_requests/summary', po_request: @po_request %>
    <% if @po_request.rows.present? %>
      <div class="card mb-2">
        <div class="card-body">
          <div class="flex-fill">
            <h6 class="text-uppercase text-black-50 mb-1">Products</h6>
          </div>

          <div class="mt-3">
            <table class="table table-bordered dt-responsive wrap-whitespace w-100" data-fixed-header="false">
              <thead>
              <tr>
                <th>Sr. No.</th>
                <th>Product</th>
                <th>Make</th>
                <th>HSN</th>
                <th data-toggle="tooltip" title="Tax Rate">T. Rate</th>
                <th>Quantity</th>
                <th data-toggle="tooltip" title="Unit of Measurement">UOM</th>
                <th data-toggle="tooltip" title="Unit Price">UP</th>
                <th data-toggle="tooltip" title="Total Price">TP</th>
                <th data-toggle="tooltip" title="Total Tax">TT</th>
                <th data-toggle="tooltip" title="Total Price with tax">TP with Tax</th>
                <th data-toggle="tooltip" title="Discount percentage">Disc. %</th>
                <th>Lead Time</th>
              </tr>
              </thead>
              <tbody>
              <% @po_request.rows.reverse.each_with_index do |row, sr_no| %>
                <% if row.product.present? %>

                  <tr>
                    <td><%= sr_no + 1 %></td>
                    <td><%= row.product.to_s %></td>
                    <td><%= row.product.try(:brand).to_s %></td>
                    <td><%= row.tax_code %></td>
                    <td><%= row.tax_rate %></td>
                    <td><%= row.quantity.to_f %></td>
                    <td><%= row.measurement_unit %></td>
                    <td><%= format_currency(row.unit_price) %></td>
                    <td><%= format_currency(row.converted_total_selling_price) %></td>
                    <td><%= format_currency(row.converted_total_tax) %></td>
                    <td><%= format_currency(row.converted_total_selling_price_with_tax) %></td>
                    <td><%= percentage(row.discount_percentage, precision: 2) %></td>
                    <td><%= format_succinct_date(row.lead_time) %></td>
                  </tr>
                <% end %>
              <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    <% end %>
    <% if @po_request.comments.persisted.size > 0 %>
      <div class="card">
        <div class="card-body">
          <div class="flex-fill">
            <h6 class="text-uppercase text-black-50 mb-1">Comments History</h6>
          </div>


          <div class="chats mb-3">
            <% @po_request.comments.each do |comment| %>
              <%= format_comment(comment) %>
            <% end %>
          </div>

        </div>
      </div>
    <% end %>
  </section>
</div>