config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/pro/web'
  post '/rate' => 'rater#create', :as => 'rate'
  get '/faq', to: 'static_pages#faq'
  mount Maily::Engine, at: '/maily' if Rails.env.development?
  mount ActionCable.server, at: '/cable'
  authenticate :overseer, lambda { |u| u.admin? } do
    mount Sidekiq::Web => '/sidekiq'
  end
  root to: 'overseers/inquiries#index'
  get '/overseers', to: redirect('/overseers/dashboard'), as: 'overseer_root'
  get '/customers', to: redirect('/customers/dashboard'), as: 'customer_root'
  get '/suppliers', to: redirect('/suppliers/dashboard'), as: 'supplier_root'

  get '/release_notes', to: 'overseers/site_updates#show'
  post '/release_notes', to: 'overseers/site_updates#create'

  devise_for :overseers, controllers: {sessions: 'overseers/sessions', omniauth_callbacks: 'overseers/omniauth_callbacks'}
  # devise_for :contacts, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords'}, path: :customers

  namespace :suppliers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'suppliers/sessions', passwords: 'suppliers/passwords'}, path: :suppliers
  end

  resources :trainings, only: %i[index show] do
    get :search, on: :collection
  end

  namespace :customers, path: '/' do
    devise_for :contacts, controllers: {sessions: 'customers/sessions', passwords: 'customers/passwords'}, path: :customers
  end

  namespace :api do
    namespace :v1 do
      resources :punchouts do
        collection do
          post 'auth'
        end
      end
    end
  end

  namespace 'callbacks' do
    resources :sales_orders do
      member do
        patch 'update'
      end
    end

    resources :sales_invoices do
      member do
        patch 'update'
      end
    end

    resources :sales_receipts

    resources :sales_shipments do
      member do
        patch 'update'
      end
    end

    resources :credit_notes do
      member do
        patch 'update'
      end
    end

    post '1de9b0a30075ae8c303eb420c103c320', to: 'image_readers#update'
    resources :purchase_orders
    resources :products

    get 'login' => '/callbacks/sessions#new'
  end

  namespace 'overseers' do
    resources :customer_feedbacks, only: :index 

    get '/docs/*page' => 'docs#index'
    resources :delivery_challans do
      collection do
        get 'next_step'
      end

      member do
        get 'preview'
        get 'relationship_map'
        get 'get_relationship_map_json'
      end
    end
    resources :payment_collection_emails
    resources :attachments
    resources :review_questions
    resources :banks
    resources :ifsc_codes do
      collection do
        get 'suggestion'
      end
    end

    resource :dashboard, controller: :dashboard do
      get 'chewy'
      get 'reset_index'
      get 'serializer'
      get 'migrations'
      get 'console'
      get 'get_status_records'
      get 'show_email_message_modal'
      post 'update_inquiry'
      post 'update_invoice_request'
      post 'approve_reject_so'
      get 'get_filtered_inquiries'
      get 'get_inquiry_tasks'
      get 'follow_up_dashboard'
      get 'sales_manager'
      get 'accounts'
      get 'sales_executive'
      get 'my_team'
      get 'get_recent_inquiries'
      get 'get_account_executive_data'
    end

    resources :tasks do
      member do
        get 'render_modal_form'
        patch 'add_comment'
      end
      scope module: 'tasks' do
        resources :comments
      end
    end

    resources :remote_requests do
      member do
        get 'show'
      end
      collection do
        get 'resend_failed_requests'
      end
    end

    resources :resync_remote_requests do
      member do
        get 'resend_failed_request'
      end
      collection do
        get 'all_requests'
      end
    end

    resources :callback_requests do
      member do
        get 'show'
      end
    end

    resources :document_creations

    resources :acl_resources do
      collection do
        get 'resource_json'
        get 'menu_resource_json'
      end
    end

    resources :notifications do
      collection do
        post 'mark_as_read'
        get 'queue'
      end
    end

    # resources :reports
    resources :reports do
      member do
        get 'export_report'
      end
    end
    resources :company_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :contact_creation_requests do
      # member do
      #   post 'exchange_with_existing_company'
      # end
      collection do
        get 'requested'
        get 'created'
      end
    end

    resources :activities, except: [:show] do
      collection do
        get 'pending'
        post 'approve_selected'
        post 'reject_selected'
        post 'add_to_inquiry'
        get 'export_all'
        get 'export_filtered_records'
      end
      member do
        get 'approve'
        get 'reject'
      end
      scope module: 'activities' do
        resources :email_messages do
          collection do
            get 'minutes_of_meeting'
            post 'minutes_of_meeting_notification'
            get 'follow_up_email'
            post 'follow_up_email_notification'
          end
        end
      end
    end

    resource :profile, controller: :profile, except: [:show, :index]
    resources :overseers do
      member do
        patch 'save_acl_resources'
        get 'get_resources'
        get 'get_menu_resources'
        get 'edit_acl'
        patch 'update_acl'
        get 'change_password'
        patch 'update_password'
        get 'becomes'
      end

      collection do
        get 'get_resources'
        get 'isp_report'
        get 'export_isp_report'
      end
    end


    resources :acl_roles do
      member do
        get 'get_acl'
        get 'get_acl_menu'
        get 'get_role_resources'
        post 'save_role'
      end
      collection do
        get 'get_default_resources'
      end
    end

    resources :annual_targets

    resources :exports, except: [:show] do
      collection do
        get 'generate_export'
      end
    end

    resources :suppliers do
      collection do
        get 'customized_index'
        get 'autocomplete'
        get 'export_all'
        get 'export_filtered_records'
      end
    end

    resources :contacts do
      collection do
        get 'autocomplete'
        get 'fetch_company_account'
      end

      member do
        get 'become'
      end
    end

    resources :sales_quotes do
    end

    resources :brands do
      collection do
        get 'autocomplete'
      end
    end

    resources :measurement_units, except: [:show] do
      collection do
        get 'autocomplete'
      end
    end

    resources :tax_codes, except: [:show] do
      collection do
        get 'autocomplete'
        get 'autocomplete_for_product'
      end
    end

    resources :addresses do
      collection do
        get 'autocomplete'
        get 'warehouse_addresses'
        get 'is_sez_params'
        get 'get_gst_code'
      end
    end

    resources :categories do
      collection do
        get 'autocomplete'
        get 'autocomplete_closure_tree'
        get 'export_all'
        get 'autocomplete_active'
      end
    end

    resources :products do
      collection do
        get 'autocomplete'
        get 'non_kit_autocomplete'
        get 'service_autocomplete'
        get 'autocomplete_mpn'
        get 'suggestion'
      end
      member do
        get 'customer_bp_catalog'
        get 'best_prices_and_supplier_bp_catalog'
        get 'sku_purchase_history'
        get 'resync'
        get 'resync_inventory'
        get 'autocomplete_suppliers'
        get 'get_product_details'
      end

      collection do
        get 'autocomplete'
        get 'pending'
        get 'export_all'
        get 'export_filtered_records'
        resources :product_imports, only: [:new, :create] do
          collection do
            get 'excel_template'
          end
        end
      end

      scope module: 'products' do
        resources :comments
      end
    end

    resources :kits do
      member do
      end

      collection do
        get 'autocomplete'
      end
    end

    resources :po_requests do
      member do
        get 'new_purchase_order'
        post 'create_purchase_order'
        get 'manager_amended'
      end
      collection do
        get 'product_resync_inventory'
      end
      scope module: 'po_requests' do
        resources :payment_requests
        resources :email_messages do
          collection do
            get 'sending_po_to_supplier'
            post 'sending_po_to_supplier_notification'
            get 'dispatch_from_supplier_delayed'
            post 'dispatch_from_supplier_delayed_notification'
            get 'material_received_in_bm_warehouse'
            post 'material_received_in_bm_warehouse_notification'
          end
        end
      end

      collection do
        get 'autocomplete'
        get 'pending_and_rejected'
        get 'cancelled'
        get 'under_amend'
        get 'amended'
        get 'pending_stock_approval'
        get 'stock_amend_requests'
        get 'stock'
        get 'completed_stock'
        get 'add_comment'
      end
      member do
        get 'render_modal_form'
        get 'render_cancellation_form'
        get 'reject_purchase_order_modal'
        patch 'rejected_purchase_order'
        patch 'cancel_porequest'
        get 'render_comment_form'
        patch 'add_comment'
      end
    end

    resources :invoice_requests do
      collection do
        get 'autocomplete'
        get 'pending'
        get 'completed'
        get 'cancelled'
      end
      member do
        get 'render_modal_form'
        patch 'cancel_invoice_request'
        patch 'add_comment'
      end
    end

    resources :ar_invoice_requests do
      collection do

app/controllers/callbacks/products_controller.rb
class Callbacks::ProductsController < Callbacks::BaseController
end

app/controllers/customers/customer_orders/comments_controller.rb
class Customers::CustomerOrders::CommentsController < Customers::CustomerOrders::BaseController
  def create
    @comment = @customer_order.comments.build(comment_params.merge(contact: current_customers_contact))
    authorize @comment

    if @comment.save
      callback_method = %w(approve reject).detect { |action| params[action] }
      send(callback_method) if callback_method.present? && policy(@customer_order).send([callback_method, '?'].join)
      redirect_to customers_customer_order_path(@customer_order), notice: flash_message(@comment, action_name)
    elsif @comment.save
      redirect_to customers_customer_order_path(@customer_order), notice: flash_message(@comment, action_name)
    else
      render 'new'
    end
  end

  private

    def comment_params
      params.require(:customer_order_comment).permit(
        :message,
          :show_to_customer
      )
    end

    def approve
      @comment.customer_order.create_approval(customer_order_comment_id: @comment.id, contact: current_customers_contact)
    end

    def reject
      @comment.customer_order.create_rejection(customer_order_comment_id: @comment.id, contact: current_customers_contact)
    end
end

app/controllers/customers/inquiries/comments_controller.rb
class Customers::Inquiries::CommentsController < Customers::Inquiries::BaseController
  def index
    @sales_order = @inquiry.sales_orders.find(params[:sales_order_id]) if params[:sales_order_id].present?
    @comments = if @sales_order.present?
      @inquiry.comments.where(sales_order_id: [nil, @sales_order.id])
    else
      @inquiry.comments.earliest
    end

    authorize @comments
  end

  def create
    @comment = @inquiry.comments.build(inquiry_comment_params.merge(overseer: current_overseer))

    authorize @comment

    if @comment.sales_order.present? && @comment.save
      callback_method = %w(approve reject).detect { |action| params[action] }
      send(callback_method) if callback_method.present? && policy(@comment.sales_order).send([callback_method, '?'].join)
      redirect_to overseers_inquiry_comments_path(@inquiry, sales_order_id: @comment.sales_order.to_param), notice: flash_message(@comment, action_name)
    elsif @comment.save
      redirect_to overseers_inquiry_comments_path(@inquiry), notice: flash_message(@comment, action_name)
    else
      render 'new'
    end
  end

  private

    def inquiry_comment_params
      params.require(:inquiry_comment).permit(
        :message,
          :sales_order_id,
          :show_in_portal
      )
    end

    def approve
      service = Services::Overseers::SalesOrders::ApproveAndSerialize.new(@comment.sales_order, @comment)
      service.call
    end

    def reject
      @comment.sales_order.create_rejection(comment: @comment, overseer: current_overseer)
      @comment.sales_order.update_attributes(status: :'Rejected')
      @comment.sales_order.update_index
    end
end

app/controllers/customers/sales_quotes/comments_controller.rb
# frozen_string_literal: true

class Customers::SalesQuotes::CommentsController < Customers::SalesQuotes::BaseController
  def index
    @comments = @sales_quote.comments
    authorize @comments
  end

  def create
    @comment = @inquiry.comments.build(comment_params.merge(contact: current_customers_contact, show_to_customer: true))
    authorize @comment

    if @comment.save
      redirect_to customers_quote_path(@sales_quote), notice: flash_message(@comment, action_name)
    else
      render 'new'
    end
  end

  private

    def comment_params
      params.require(:inquiry_comment).permit(
        :message
      )
    end
end

app/controllers/overseers/companies/products_controller.rb
class Overseers::Companies::ProductsController < Overseers::Companies::BaseController
  def index
    base_filter = {
        base_filter_key: 'id',
        base_filter_value: Product.joins(:inquiry_products, :inquiry_product_suppliers).where(inquiry_product_suppliers: { supplier_id: params[:company_id] }).pluck(:id)
    }

    service = Services::Overseers::Finders::Products.new(params.merge(base_filter))
    service.call
    @products = service.records
    @indexed_products = service.indexed_records
    authorize_acl @products
  end
end

app/controllers/overseers/customer_orders/comments_controller.rb
class Overseers::CustomerOrders::CommentsController < Overseers::CustomerOrders::BaseController
  def create
    @comment = @customer_order.comments.build(comment_params.merge(overseer: current_overseer))
    authorize_acl :customer_order
    if @comment.save
      redirect_to overseers_customer_order_path(@customer_order), notice: flash_message(@comment, action_name)
    else
      'new'
    end
  end

  private

    def comment_params
      params.require(:customer_order_comment).permit(
        :message,
          :show_to_customer
      )
    end
end

app/controllers/overseers/inquiries/comments_controller.rb
class Overseers::Inquiries::CommentsController < Overseers::Inquiries::BaseController
  before_action :set_notification, only: [:create]

  def index
    @sales_order = @inquiry.sales_orders.find(params[:sales_order_id]) if params[:sales_order_id].present?
    @comments = if @sales_order.present?
      @inquiry.comments.where(sales_order_id: [@sales_order.id]).latest
      # @inquiry.comments.where(sales_order_id: [nil, @sales_order.id]).latest
    else
      @inquiry.comments.latest
    end

    @internal_comments = @comments.internal_comments.page(params[:internal]).per(10)
    @customer_comments = @comments.customer_comments.page(params[:customer]).per(10)
    authorize_acl @comments
  end

  def create
    @comment = @inquiry.comments.build(inquiry_comment_params.merge(overseer: current_overseer))

    authorize_acl @comment

    if @comment.sales_order.present? && @comment.save
      callback_method = %w(approve reject).detect { |action| params[action] }
      send(callback_method) if callback_method.present? && policy(@comment.sales_order).send([callback_method, '?'].join)
      @notification.send_order_comment(
        @inquiry.inside_sales_owner,
          action_name.to_sym,
          @comment.sales_order,
          overseers_inquiry_comments_path(@inquiry, sales_order_id: @sales_order.to_param, show_to_customer: false),
          callback_method, @inquiry.inquiry_number.to_s, @comment.message
      )
      redirect_to overseers_inquiry_comments_path(@inquiry, sales_order_id: @comment.sales_order.to_param, show_to_customer: inquiry_comment_params[:show_to_customer]), notice: flash_message(@comment, action_name)
    elsif @comment.save
      redirect_to overseers_inquiry_comments_path(@inquiry, show_to_customer: inquiry_comment_params[:show_to_customer]), notice: flash_message(@comment, action_name)
    else
      render 'new'
    end
  end

  private

    def inquiry_comment_params
      params.require(:inquiry_comment).permit(
        :message,
          :sales_order_id,
          :show_to_customer
      )
    end

    def approve
      service = Services::Overseers::SalesOrders::ApproveAndSerialize.new(@comment.sales_order, @comment)
      Services::Overseers::Inquiries::UpdateStatus.new(@comment.sales_order, :order_approved_by_sales_manager).call
      service.call
    end

    def reject
      @comment.sales_order.create_rejection(comment: @comment, overseer: current_overseer)
      @comment.sales_order.update_attributes(status: :'Rejected')
      Services::Overseers::Inquiries::UpdateStatus.new(@comment.sales_order, :order_rejected_by_sales_manager).call
      @comment.sales_order.update_index
    end
end

app/views/overseers/products/comments/index.html.erb
<% if @product.inquiry_products.first.try(:inquiry) %>
  <% content_for :heading_button do %>
    <div class="d-flex flex-row">
      <a class="d-sm-block btn btn-warning btn-rounded align-self-center btn-block-sm-down mr-1 bmro-button" href="<%= edit_overseers_product_path(@product) %>" target="_blank"><i class="bmro-fa-pencil"></i>Edit</a>
      <%= link_to edit_overseers_inquiry_path(@product.inquiry_products.first.try(:inquiry)), target: '_blank', class: "d-sm-block btn btn-dark btn-rounded align-self-center btn-block-sm-down bmro-button" do %>
        <i class="bmro-fa-external-link"></i> Check Inquiry
      <% end %>
    </div>
  <% end %>
<% end %>

<% content_for :heading_byline do %>
<!--   This will <em>'update/approve/reject <%= @product %>'</em> and log it under
  <strong><%= current_overseer.full_name %></strong>. -->
<% end %>

<%= render layout: 'shared/layouts/form' do %>
  <div class="card">
    <div class="card-body">
      <div>
        <h6 class="text-uppercase text-black-50 mb-1 bmro-form-heading">Product Details</h6>
        <div class="form-row">
          <div class="col-6 col-md-3 mb-2">
            <strong class="d-block bmro-summary-heading">Product</strong>
            <div class="bmro-summary-data">
            <%= @product %>
            </div>
          </div>

          <% if @product.sku? %>
            <div class="col-6 col-md-3 mb-2">
              <strong class="d-block bmro-summary-heading">BM Number</strong>
              <div class="bmro-summary-data">
              <%= @product.sku %>
              </div>
            </div>
          <% end %>

          <% if @product.category.present? %>
            <div class="col-6 col-md-3 mb-2">
              <strong class="d-block bmro-summary-heading">Category</strong>
              <div class="bmro-summary-data">
              <%= @product.category %>
              </div>
            </div>
          <% end %>

          <% if @product.brand.present? %>
            <div class="col-6 col-md-3 mb-2">
              <strong class="d-block bmro-summary-heading">Brand</strong>
              <div class="bmro-summary-data">
              <%= @product.brand %>
              </div>
            </div>
          <% end %>

          <% if @product.mpn? %>
            <div class="col-6 col-md-3 mb-2">
              <strong class="d-block">Manufacturer Part Number</strong>
              <div class="bmro-summary-data">
              <%= @product.mpn %>
              </div>
            </div>
          <% end %>

          <div class="col-6 col-md-3 mb-2">
            <strong class="d-block bmro-summary-heading">Is Service?</strong>
            <div class="bmro-summary-data">
            <%= format_boolean(@product.is_service) %>
            </div>
          </div>

        </div>
      </div>
      <div class="mt-3">
        <h6 class="text-uppercase text-black-50 mb-1 d-block bmro-form-heading">Accounting and Logistics</h6>
        <div class="form-row">
          <% if @product.tax_code.present? %>
            <div class="col-6 col-md-3 mb-2">
              <strong class="d-block bmro-summary-heading">Tax Code</strong>
              <div class="bmro-summary-data">
              <%= @product.tax_code %>
              </div>
            </div>
          <% end %>

          <% if @product.measurement_unit %>
            <div class="col-6 col-md-3 mb-2">
              <strong class="d-block bmro-summary-heading">Unit of Measurement</strong>
              <div class="bmro-summary-data">
              <%= @product.measurement_unit %>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <%= simple_form_for([:overseers, @new_comment], :html => {:class => 'card needs-validation mt-3', :'novalidate' => '', :'data-parsley-validate' => ''}) do |f| %>
    <div class="card-body">
      <% if @comments.persisted.size > 0 %>
        <div class="chats">
          <% @comments.persisted.each do |comment| %>
            <div class="media chat-item comments-wrap">
              <div class="media-body">
                <div class="chat-item-title">
                  <span class="chat-item-author"><%= comment.created_by.full_name %></span>
                  <span class="bmro-comment-age"><span class="mr-1"><strong>
                    <% if comment.merged? %><span class="badge badge-secondary">Merged</span><% end %>
                    <% if comment.approval.present? %><span class="badge badge-success">Approved</span><% end %>
                    <% if comment.rejection.present? %><span class="badge badge-danger">Rejected</span><% end %></strong></span><%= time_ago_in_words(comment.created_at) %>
                    ago</span>
                </div>
                <div class="chat-item-body">
                  <p><%= comment.message %></p>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>

      <%= render 'shared/snippets/form_errors', f: f %>

      <%= f.input :message, required: true, :placeholder => 'Type message', input_html: {:'data-parsely-no-valid-feedback' => ''} %>

      <div class="flex-fill">
        <div class="form-row">
          <div class="col-lg-6">
            <div class="form-row">
              <div class="col-12 col-md-2">
                <%= f.submit 'Reply', name: 'reply', class: 'btn btn-dark btn-block bmro-button' %>
              </div>
              <div class="col-12 col-md-5 mt-1 mt-md-0">
                <%= f.submit 'Reply and Approve', name: 'approve', class: 'btn btn-success btn-block bmro-button' if is_authorized(@product, 'approve') && policy(@product).approve? %>
              </div>
              <div class="col-12 col-md-5 mt-1 mt-md-0">
                <%= f.submit 'Reply and Reject', name: 'reject', class: 'btn btn-danger btn-block bmro-button' if is_authorized(@product, 'reject') && policy(@product).reject? %>
              </div>
            </div>
          </div>

          <div class="col-lg-6 text-right">
            <%= content_tag :div, class: 'd-flex flex-row align-items-start justify-content-end mt-1 mt-md-0' do %>
              <div class="mr-1">
                <%= f.input :merge_with_product_id, :as => :select, label_method: :to_s, include_blank: "Type SKU number, name, or brand", input_html: {class: 'select2-ajax bmro-form-input', :'data-source' => autocomplete_overseers_products_path}, label: false %>
              </div>
              <div>
                <%= f.submit 'Merge', name: 'merge', class: 'btn btn-warning float-right bmro-button' %>
              </div>
            <% end if is_authorized(@product, 'merge')  %>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>